version: "3.9"
services:
    
## REDIS CACHE
  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
      
## KAFKA
  zookeeper:
      image: confluentinc/cp-zookeeper:7.3.0
      hostname: zookeeper
      container_name: zookeeper
      ports:
        - "2181:2181"
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  broker:
      image: confluentinc/cp-kafka:7.3.0
      hostname: broker
      container_name: broker
      depends_on:
        - zookeeper
      ports:
        - "29092:29092"
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR



  # PYROGI
  generator:
    image: mocker
    container_name: generator
    environment:
      - REDIS_HOST=redis
    ports:
      - "8001"

  proxy:
    image: flasky
    container_name: proxy
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:5000"

  pyrogi:
    image: pyrogi
    container_name: pyrogi
    links:
      - "proxy:proxys"
    ports:
      - "8000:8000"

  producer-users:
    image: producer
    container_name: producer-users
    command: python code/users.py
    links:
      - "proxy:proxys"
    ports:
      - "8002:8002"

  producer-events:
    image: producer
    container_name: producer-events
    command: python code/events.py
    links:
      - "proxy:proxys"
    ports:
      - "8003:8003"

  consumer-users:
    image: consumer
    container_name: consumer-users
    command: python code/users.py
    ports:
      - "8004:8004"

  consumer-events:
    image: consumer
    container_name: consumer-events
    command: python code/events.py
    ports:
      - "8005:8005"